// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage0":return img`
. . . . . f f f f f f . . . . . 
. . . . f 4 4 4 4 4 4 f . . . . 
. . . . . f d d d d f . . . . . 
. . . . . . f d d f . . . . . . 
. . . . . . f 4 4 f . . . . . . 
. . . . . . f 4 4 f . . . . . . 
. . . . . . f 4 4 f . . . . . . 
. . . . f f f f f f f f . . . . 
. . . f 2 2 2 2 2 2 2 2 f . . . 
. . . f 2 1 1 1 2 2 2 2 f . . . 
. . . f 2 1 1 1 1 2 2 2 f . . . 
. . . f 2 1 1 1 1 2 2 2 f . . . 
. . . f 2 2 1 1 2 2 2 2 f . . . 
. . . f 2 2 2 2 2 2 2 2 f . . . 
. . . f 2 2 2 2 2 2 2 2 f . . . 
. . . . f f f f f f f f . . . . 
`;
            case "image3":
            case "myImage1":return img`
. . . . . . . . . . . . . . . . 
b b b b b b b b b b b b b b b b 
b b b b b b b b b b b b b b b b 
b b b 6 b b b b b b b 6 b b b b 
. b b b 3 3 3 3 3 3 3 b b b b . 
. b b b 3 3 3 3 3 3 3 b b b . . 
. b b b b 3 3 3 3 3 b b b . . . 
. . b b b b 3 3 3 b b b b . . . 
. . b b b b b b b b b b b . . . 
. . . b b b b b b b b b b . . . 
. . . b b b b b b b b b b . . . 
. . . b b b b b b b b b b . . . 
. . . b b b b b b b b b . . . . 
. . . b b b b b b b b b . . . . 
. . . b b b b b b b b b . . . . 
. . . . b b b b b b b b . . . . 
`;
            case "image4":
            case "myImage2":return img`
.........7799.........779977.........9977....77...........7777........
...99..99999999999..997777777799.....779999..77.....77779977..........
...99..99999999999..997777777799.....779999..77.....77779977..........
...9933337777..9996699774477..77666667777777766667777799ee777777......
...9933337777..9996699774477..77666667777777766667777799ee777777......
.....11337799..7773333777733117766677776633667777666776633337777......
.....11337799..7773333777733117766677776633667777666776633337777......
999..779977..773331177667777777777777773311776677ccc7777113377........
999..779977..773331177667777777777777773311776677ccc7777113377........
999..779977..773331177667777777777777773311776677ccc7777113377........
7ee99449944777777777333377669999666777777667766666667777667777..77....
7ee99449944777777777333377669999666777777667766666667777667777..77....
...7733339977777773377777799666666666776677669966666777777667777......
...7733339977777773377777799666666666776677669966666777777667777......
.99..33119977997777777779999117777777776666776677777776666776666......
.99..33119977997777777779999117777777776666776677777776666776666......
.77777777667744333776677667733777776677666677776677733777766776677....
.77777777667744333776677667733777776677666677776677733777766776677....
.77777777667744333776677667733777776677666677776677733777766776677....
...773333..7777777777799777777777777711339977333311133776677cc6677....
...773333..7777777777799777777777777711339977333311133776677cc6677....
...337799779999777777777999977777777733779977337777777773311777777....
...337799779999777777777999977777777733779977337777777773311777777....
799999999777799999..7799667777777777777776677777777777999966..6666....
799999999777799999..7799667777777777777776677777777777999966..6666....
.999977777777eeeee7766333333667777766777766777766777666677667777......
.999977777777eeeee7766333333667777766777766777766777666677667777......
.999977777777eeeee7766333333667777766777766777766777666677667777......
.99331133777777777777733117766777776677ee66777777666776677............
.99331133777777777777733117766777776677ee66777777666776677............
.99333377337777...77779977777777777667777667777666667766777777..66....
.99333377337777...77779977777777777667777667777666667766777777..66....
9....7777777777777..777777777777777337777663366777776677776666........
9....7777777777777..777777777777777337777663366777776677776666........
9..999977......7777777337777777733311667733117766777666677..6666......
9..999977......7777777337777777733311667733117766777666677..6666......
9..999977......7777777337777777733311667733117766777666677..6666......
...999999..777733377..7777..7799666336677cccc6666777663311667766......
...999999..777733377..7777..7799666336677cccc6666777663311667766......
.....77......77111337777..77777766677666699773311777777733777766......
.....77......77111337777..77777766677666699773311777777733777766......
.........7777.........77..999977777ee77666699..77.......666666........
.........7777.........77..999977777ee77666699..77.......666666........
.........9977.........777799996666666776677....77...66................
.........9977.........777799996666666776677....77...66................
.........9977.........777799996666666776677....77...66................
.........77.....................444eeeeeeee..66.......................
.........77.....................444eeeeeeee..66.......................
................................44466eeee66...........................
................................44466eeee66...........................
................................444eeeeeecc...........................
................................444eeeeeecc...........................
................................444eeeeeecc...........................
................................444eeeeeecc...........................
................................444eeeeeecc...........................
..............................ee444eeeeccee...........................
..............................ee444eeeeccee...........................
..............................eeeeeeeeeccee...........................
..............................eeeeeeeeeccee...........................
............................4444eeeeeeeccccee.........................
............................4444eeeeeeeccccee.........................
........................444444eeeeeeeeecccccc.........................
........................444444eeeeeeeeecccccc.........................
........................444444eeeeeeeeecccccc.........................
..................eeeeee4444eeee...eecceecccccceeccc..................
..................eeeeee4444eeee...eecceecccccceeccc..................
.............eeeeeeeee..44eeee.....eeccee..cccccceeecc................
.............eeeeeeeee..44eeee.....eeccee..cccccceeecc................
.......eeeeee.........ee.............ee......eeeeeee..cccceeee........
.......eeeeee.........ee.............ee......eeeeeee..cccceeee........
`;
            case "image1":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . b b b b b b b b b b b b 
. . . . b b b b b b b b b b b b 
. . . . b b 1 b b b b b b b b . 
3 3 3 3 b b f b b b 1 b b b b . 
3 . . . . b b 1 1 b f b b b b 3 
3 . . . . b b b b b b b b b . 3 
3 . . . . b b b b b b b b b . 3 
3 . . . . b b b b b b b b b . 3 
. . . . . 3 . . . b b b b b . 3 
. . . . . 3 . . . . . . 3 . . . 
. . . . . 3 . . . . . . 3 . . . 
. . . . . 3 . . . . . . 3 . . . 
. . . . . 3 . . . . . . 3 . . . 
3 3 3 3 3 3 . . . . . . 3 3 3 3 
`;
            case "image7":
            case "myImage5":return img`
. . . . . . . . . . . . . . . . 
. . . f . . . . . . . . . f . . 
. . f . f . f f f f f . f . f . 
. . . . . f f f f f f f . . . . 
. . f f f f f f f f f f f f f . 
. f . . . f f f f f f f . . . f 
f . . f f f f f f f f f f f . . 
. . f . . f 2 f f f 2 f . . f . 
. f . . f . f f f f f . f . . f 
f . . f . . f . . . f . . f . . 
. . . f . . . f . f . . . f . . 
. . . f . . . . . . . . . f . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image6":
            case "myImage4":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . f . . . f . . . . . 
. . . f . . f f f f f . . f . . 
. . f f f . f 2 f 2 f . f f f . 
. f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f f f f f f f f f f f f f f f 
f f . f . f f f f f f f . f . f 
f . . . . . f f f f f . . . . . 
. . . . . . . f . f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image8":
            case "myImage6":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f 5 5 5 5 5 f . . . . . 
. . . . f 5 5 5 5 5 5 f . . . . 
. . . f 5 f 5 5 5 f 5 f . . . . 
. . . f 5 f 5 5 5 f 5 7 f . . . 
. . . f 5 5 5 5 5 5 5 7 f . . . 
. . . . f 7 7 7 7 7 7 f . . . . 
. . . . . f f f f f f f . . . . 
. . . f f 5 5 f 5 5 7 f f . . . 
. . f 5 5 5 f 5 5 5 7 f 7 f . . 
. f 5 5 f 7 7 7 7 7 f 5 7 7 f . 
. f 7 5 5 f f f f f 5 5 7 f 7 f 
. f 7 5 5 5 5 5 5 5 5 5 7 f 7 f 
. . f 7 7 7 7 7 7 7 7 7 f f 7 f 
`;
            case "image9":
            case "myImage7":return img`
..................
......fffff.......
....ff11111ff.....
...f111111111f....
..f11111111111f...
..f11111111111f...
.f111f11f111111f..
.f11ff11ff11111f..
.f1fff11fff1111f..
.f1111111111111f..
.f1111111111111f..
.f1111ff111ff11f..
f1f1111111f1111f..
f1ff111111f1f111f.
.f..ff1111ff11111f
......fff1111111f.
.........fffffff..
`;
            case "image11":
            case "myImage9":return img`
..............................
..............................
.......................ff.....
.....................ffddf....
....................fdddef....
..................ffdddef.....
................ffddddeef.....
..........ffffffddddeeef......
.........fddddddddeeeeef......
..........feeeeddddeeeef......
...........fffeeeedddef.......
..............fffeeeeeef......
.............f5fffffeeeef.....
............ff5ff5ffffeeef....
...........f8ffff5ffff8feef...
..........f8fffffffffff8ff....
..........f888fff8888888f.....
..........ff888888fff88f......
.........fddf888ff888888f.....
.........fddf88fff888888f.....
..........ff888ddf888888f.....
..........f8f88ddf888888f.....
..........f8f88fff88888f......
..........f88f8888f8888f......
..........f888f888f8888f......
..........f8888ff88f88f8f.....
.........f8888888888ff888f....
..........ffffffffff..fff.....
..............................
..............................
`;
            case "image12":
            case "myImage10":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..................ff..........
................ffdd..........
...............fddde..........
............ffdddeef..........
......fdddddddeeeef...........
.......feeeddddeeef...........
........ffeeeeddef............
..........fffeeeeef...........
..........5ffffeeeef..........
........f8fff5fff8fe..........
.......f8fffffffff8f..........
.......ff88888ff88f...........
......fddf88ff88888f..........
......fddf8fff88888f..........
.......ff88ddf88888f..........
.......f8f8fff8888f...........
.......f888888f888f...........
.......f88f888f888f...........
.......f888ff8888f8f..........
..............................
..............................
..............................
`;
            case "image13":
            case "myImage11":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
e e e e e e e e e e e e e e e e 
e e e e e e 1 1 1 1 e e e e e e 
4 4 4 4 4 1 f f f f 1 4 4 4 4 4 
e e e e e e 1 1 1 1 e e e e e e 
e e e e e e e 1 1 e e e e e e e 
e e e e e e e e e e e e e e e e 
e e e e e e e e e e e e e e e e 
e e e e e e e e e e e e e e e e 
`;
            case "image14":
            case "myImage12":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. . f d b f f f f f f b d f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e 4 d d d d d d 4 e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f b b b b b b f 4 e . . 
. . 4 d f b b b b b b f d 4 . . 
. . 4 4 f e e 5 5 e e f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image15":
            case "myImage13":return img`
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. . f d b f f f f f f b d f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f f f f d d d d d e e f . . 
. f d d d d f 4 4 4 e e f . . . 
. f b b b b f b b b b f 4 e . . 
. f b b b b f b b b b f d 4 . . 
. . f c c f e 5 5 e e f 4 4 . . 
. . . f f f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`;
            case "image5":
            case "myImage3":return img`
. . . . . . . . . . . . . . . . 
. . . c . . . . . . . . . . . . 
. . c b b b b b b b b b b . . . 
. c c b d d d d d d d d d b . . 
. c c b d d d d d d d d d b . . 
. . c b b b b b b b b b b . . . 
. . . c . . . . . . . . . . . . 
. . . . . . . . b b . . . . . . 
. . . . . b b b 3 b . . . . . . 
. . b b b b b 3 3 b . . . . . . 
. . b b b b 3 3 3 b . . . . . . 
. . b b b b 3 3 3 b . . . . . . 
. . b b b b b 3 3 b . . . . . . 
. . . . b b b b 3 b . . . . . . 
. . . . . . . . b b . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image16":
            case "myImage14":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image17":
            case "myImage15":return img`
....................
....................
....................
....................
....................
....................
....................
....................
...........e........
.........ee.........
........ee..........
.......ee...........
......ee............
.....ee.............
....ee..............
...ee...............
..eee...............
.eee................
.ee.................
....................
`;
            case "image20":
            case "myImage18":return img`
. . b b b b b b b c c b b b b . 
. b e e e e e e b b c e e c b b 
b e 4 4 4 e e e b b c e e e b b 
b 4 4 4 4 4 e e b b c e e e b . 
b 4 4 4 4 4 e e b b c e e e b . 
b 4 4 4 4 4 e e b b c e e e b . 
b 4 4 4 4 4 e e b b b c e e b . 
b 4 4 4 4 4 e e d c c b e e b . 
b 4 4 4 4 4 e e d c c b e e b . 
b 4 4 4 4 4 e e b b b c e e b . 
b 4 4 4 4 4 e e b b c e e e b . 
b 4 4 4 4 4 e e b b c e e e b . 
b 4 4 4 4 4 e e b b c e e e b . 
b e 4 4 4 e e e b b c e e e b b 
. b e e e e e e b b c e e c b b 
. . b b b b b b b c c b b b b . 
`;
            case "image18":
            case "myImage16":return img`
. . b b b b b b b b b b b b . . 
. b e 4 4 4 4 4 4 4 4 4 4 e b . 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e 4 4 4 4 4 4 4 4 4 4 4 4 e b 
b e e 4 4 4 4 4 4 4 4 4 4 e e b 
b e e e e e e e e e e e e e e b 
b e e e e e e e e e e e e e e b 
b b b b b b b d d b b b b b b b 
c b b b b b b c c b b b b b b c 
c c c c c c b c c b c c c c c c 
b e e e e e c b b c e e e e e b 
b e e e e e e e e e e e e e e b 
b c e e e e e e e e e e e e c b 
b b b b b b b b b b b b b b b b 
. b b . . . . . . . . . . b b . 
`;
            case "image19":
            case "myImage17":return img`
. b b b b c c b b b b b b b . . 
b b c e e c b b e e e e e e b . 
b b e e e c b b e e e 4 4 4 e b 
. b e e e c b b e e 4 4 4 4 4 b 
. b e e e c b b e e 4 4 4 4 4 b 
. b e e e c b b e e 4 4 4 4 4 b 
. b e e c b b b e e 4 4 4 4 4 b 
. b e e b c c d e e 4 4 4 4 4 b 
. b e e b c c d e e 4 4 4 4 4 b 
. b e e c b b b e e 4 4 4 4 4 b 
. b e e e c b b e e 4 4 4 4 4 b 
. b e e e c b b e e 4 4 4 4 4 b 
. b e e e c b b e e 4 4 4 4 4 b 
b b e e e c b b e e e 4 4 4 e b 
b b c e e c b b e e e e e e b . 
. b b b b c c b b b b b b b . . 
`;
            case "image21":
            case "myImage19":return img`
. . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . 
. . . . . 5 5 5 5 5 5 5 . . . . . 
. . . . 5 4 4 4 4 4 4 4 5 . . . . 
. . . 5 4 4 4 4 4 4 4 4 4 5 . . . 
. . . 5 4 4 4 4 4 4 4 4 4 5 . . . 
. . . 5 4 4 4 4 4 4 4 4 4 5 . . . 
. . . 5 4 4 4 4 4 4 4 4 4 5 . . . 
. . . 5 4 4 4 4 4 4 4 4 4 5 . . . 
. . . 5 4 4 4 4 4 4 4 4 4 5 . . . 
. . . 5 4 4 4 4 4 4 4 4 4 5 . . . 
. . . . 5 4 4 4 4 4 4 4 5 . . . . 
. . . . . 5 5 5 5 5 5 5 . . . . . 
. . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . . 
`;
            case "image10":
            case "myImage8":return img`
...................................
............fffffffff..............
...........f111111111f.............
..........fd1111111111f............
..........fd1111111111f............
.........fdd11111111111f...........
.........fddd1111111111f...........
.........fddfff111fff11f...........
.........fddfff111fff11f...........
..........fddff111ff11f............
..........fdddd1f11111f............
...........ffdddf111ff.............
.............fdd111f...............
.............fdf1f1f...............
..............fffff................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
...................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim1":
            case "anim3":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f b b f f f f f . . 
. . f f e b e b b e b e f f . . 
. . f e b f b f f b f b e f . . 
. . f f f b b e e b b f f f . . 
. f f e f b f e e f b f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f d f . 
. . e 4 f b b b b b b f 4 b f . 
. . 4 d f b b b b b b f d b f . 
. . 4 4 f e e e e e e f 4 c f . 
. . . . . f f f f f f . . f . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f . . . . . . . 
. . . f f e e e e f f . . . . . 
. . f e e e f f e e e f . . . . 
. . f f f f b b f f f f . . . . 
. f f e b e b b e b e f f . . . 
. f e b f b f f f b f e f . . . 
. f f f b f e e b b f f f . . . 
. f e b f f e e b f e e f . . . 
f f e f f e e e f e e e f f . . 
f f e e e e e e e e e e f d f . 
. . f e e e e e e e e f f b f . 
. . e f b b b b b b f 4 f b f . 
. . 4 f b b b b b e d d f c f . 
. . e f e e e e e e e 4 f f . . 
. . . f f f . . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f b b f f f f f . . 
. . f f e b e b b e b e f f . . 
. . f e b f b f f b f b e f . . 
. . f f f b b e e b b f f f . . 
. f f e f b f e e f b f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f d f . 
. . e 4 f b b b b b b f 4 b f . 
. . 4 d f b b b b b b f d b f . 
. . 4 4 f e e e e e e f 4 c f . 
. . . . . f f f f f f . . f . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . f f f f . . . . . . . 
. . . f f e e e e f f . . . . . 
. . f e e e f f e e e f . . . . 
. . f f f f b b f f f f . . . . 
. f f e b e b b e b e f f . . . 
. f e f b f f f b f b e f . . . 
. f f f b b e e f b f f f . . . 
. f e e f b e e f f b e f . . . 
. f e e e f e e e f f e f f . . 
. f e e e e e e e e e e f f . . 
. f f e e e e e e e e f c f . . 
. e 4 f b b b b b b f e b f . . 
. 4 d d e b b b b b f 4 b f . . 
. e 4 e e e e e e e f e d f . . 
. . . . . . . . f f f . f . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim0":
            case "anim4":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f b b f f f f f . . 
. . f f e b e b b e b e f f . . 
. . f e b f b f f b f b e f . . 
. . f f f b b e e b b f f f . . 
. f f e f b f e e f b f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f b b b b b b f 4 e . . 
. . 4 d f b b b b b b f d 4 . . 
. . 4 4 f e e e e e e f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f b b f f f f . . . 
. . f f e b e b b e b e f f . . 
. . f e b f b f f f b f e f . . 
. . f f f b f e e b b f f f . . 
. . f e b f f e e b f e e f . . 
. f f e f f e e e f e e e f f . 
. f f e e e e e e e e e e f f . 
. . . f e e e e e e e e f . . . 
. . . e f b b b b b b b 4 e . . 
. . . 4 f b b b b b b d d 4 . . 
. . . e f e e e e e e e 4 . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . f f f f f b b f f f f f . . 
. . f f e b e b b e b e f f . . 
. . f e b f b f f b f b e f . . 
. . f f f b b e e b b f f f . . 
. f f e f b f e e f b f e f f . 
. f e e f f e e e e f e e e f . 
. . f e e e e e e e e e e f . . 
. . . f e e e e e e e e f . . . 
. . e 4 f b b b b b b f 4 e . . 
. . 4 d f b b b b b b f d 4 . . 
. . 4 4 f e e e e e e f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f e e e e f f . . . . 
. . . f e e e f f e e e f . . . 
. . . f f f f b b f f f f . . . 
. . f f e b e b b e b e f f . . 
. . f e f b f f f b f b e f . . 
. . f f f b b e e f b f f f . . 
. . f e e f b e e f f b e f . . 
. f f e e e f e e e f f e f f . 
. f f e e e e e e e e e e f f . 
. . . f b b b b b b b e f . . . 
. . e 4 b b b b b b b f e . . . 
. . 4 d d e e e e e e f 4 . . . 
. . . 4 e e f f f f f f e . . . 
. . . . . . . . . f f f . . . . 
`];
            case "myAnim":
            case "anim2":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. . f d b f f f f f f b d f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e 4 d d d d d d 4 e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f b b b b b b f 4 e . . 
. . 4 d f b b b b b b f d 4 . . 
. . 4 4 f e e 5 5 e e f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. f f d b f f f f f f b d f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . . f e 4 d d d d 4 e f e . . 
. . f e f b b b b e d d 4 e . . 
. . e 4 f b b b b e d d e . . . 
. . . . f e e 5 5 f e e . . . . 
. . . . f f f f f f f . . . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. . f d b f f f f f f b d f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f e 4 d d d d d d 4 e f . . 
. . . f e e 4 4 4 4 e e f . . . 
. . e 4 f b b b b b b f 4 e . . 
. . 4 d f b b b b b b f d 4 . . 
. . 4 4 f e e 5 5 e e f 4 4 . . 
. . . . . f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. f f d b f f f f f f b d f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. . f e 4 1 f d d f 1 4 e f . . 
. . e f e 4 d d d d 4 e f . . . 
. . e 4 d d e b b b b f e f . . 
. . . e d d e b b b b f 4 e . . 
. . . . e e f 5 5 e e f . . . . 
. . . . . f f f f f f f . . . . 
. . . . . . . . . f f f . . . . 
`];
            case "heroWalkShieldLeft0":
            case "anim9":return [img`
. . . . . f f f f f f . . . . . 
. . . f f e e e e f b f . . . . 
. . f f e e e e f b b b f . . . 
. . f e e e f f d d d d f . . . 
. . f f f f d d b b b b d f . . 
. . f e b b b f f f f e b f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . f f e e 4 e e e f b b f . 
. . . . f b b b 4 d d e b b f . 
. . . . e b b b e d d e b f . . 
. . . . f 4 4 4 f e e f f . . . 
. . . . . f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f b f . . . . 
. . f f e e e e f b b b f . . . 
. . f e e e f f d d d d f . . . 
. . f f f f d d b b b b d f . . 
. . f e b b b f f f f e b f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . . f e e 4 e e e f b b f . 
. . . . f 2 b b 4 d d e b b f . 
. . . f f b 4 4 e d d e b f . . 
. . . f f f f f f e e f f . . . 
. . . . f f . . . f f f . . . . 
`, img`
. . . . . f f f f f f . . . . . 
. . . f f e e e e f b f . . . . 
. . f f e e e e f b b b f . . . 
. . f e e e f f d d d d f . . . 
. . f f f f d d b b b b d f . . 
. . f e b b b f f f f e b f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . f f e e 4 e e e f b b f . 
. . . . f b b b 4 d d e b b f . 
. . . . e b b b e d d e b f . . 
. . . . f 4 4 4 f e e f f . . . 
. . . . . f f f f f f . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . f f e e e e f b f . . . . 
. . f f e e e e f b b b f . . . 
. . f e e e f f d d d d f . . . 
. . f f f f d d b b b b d f . . 
. . f e b b b f f f f e b f . . 
. f f f f f f f e e e f f f . . 
. f f e 4 4 e b f 4 4 e e f . . 
. f e e 4 d 4 1 f d d e f f . . 
. . f e e e 4 d d d d f d d f . 
. . . . f e e 4 e e e f b b f . 
. . . . f b b b 4 d d e b b f . 
. . . f f 4 4 4 e d d e b f . . 
. . . f f f f f f e e f f . . . 
. . . . f f . . . f f f . . . . 
`];
            case "myAnim2":
            case "anim5":return [img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f b f . . . 
. . . f f e e e e f b b b f . . 
. . . f e e e f f 1 1 1 1 f . . 
. . . f f f f 1 1 b b b b 1 f . 
. . . f e b b b f f f f e b f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e b b b f . . . 
. . . . . e d d e b b b f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f b f . . . 
. . . f f e e e e f b b b f . . 
. . . f e e e f f 1 1 1 1 f . . 
. . . f f f f 1 1 b b b b 1 f . 
. . . f e b b b f f f f e b f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e e e d d d f . . . 
. . . . . f 4 d d e 4 e f . . . 
. . . . . f e d d e b b f . . . 
. . . . f f f e e f 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`, img`
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f b f . . . 
. . . f f e e e e f b b b f . . 
. . . f e e e f f 1 1 1 1 f . . 
. . . f f f f 1 1 b b b b 1 f . 
. . . f e b b b f f f f e b f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . f f e e 4 4 4 e f . . . 
. . . . . 4 d d e b b b f . . . 
. . . . . e d d e b b b f . . . 
. . . . . f e e f 4 5 5 f . . . 
. . . . . . f f f f f f . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f f f . . . . 
. . . . f f e e e e f b f . . . 
. . . f f e e e e f b b b f . . 
. . . f e e e f f 1 1 1 1 f . . 
. . . f f f f 1 1 b b b b 1 f . 
. . . f e b b b f f f f e b f . 
. . f f f f f f f e e e f f f . 
. . f f e 4 4 e b f 4 4 e e f . 
. . f e e 4 d 4 1 f d d e f . . 
. . . f e e e 4 d d d d f . . . 
. . . . 4 d d e 4 4 4 e f . . . 
. . . . e d d e b b b b f . . . 
. . . . f e e f 4 4 5 5 f f . . 
. . . . f f f f f f f f f f . . 
. . . . . f f . . . f f f . . . 
`];
            case "heroWalkShieldLeft":
            case "anim8":return [img`
. . . . . f f f f f f . . . . . 
. . . . f b f e e e e f f . . . 
. . . f b b b f e e e e f f . . 
. . . f d d d d f f e e e f . . 
. . f d b b b b d d f f f f . . 
. . f b e f f f f b b b e f . . 
. . f f f e e e f f f f f f f . 
. . f e e 4 4 f b e 4 4 e f f . 
. . f f e d d f 1 4 d 4 e e f . 
. f d d f d d d d 4 e e e f . . 
. f b b f e e e 4 e e f f . . . 
. f b b e d d 4 b b b f . . . . 
. . f b e d d e b b b e . . . . 
. . . f f e e f 4 4 4 f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f b f e e e e f f . . . 
. . . f b b b f e e e e f f . . 
. . . f d d d d f f e e e f . . 
. . f d b b b b d d f f f f . . 
. . f b e f f f f b b b e f . . 
. . f f f e e e f f f f f f f . 
. . f e e 4 4 f b e 4 4 e f f . 
. . f f e d d f 1 4 d 4 e e f . 
. f d d f d d d d 4 e e e f . . 
. f b b f e e e 4 e e f . . . . 
. f b b e d d 4 b b b f . . . . 
. . f b e d d e 4 4 4 f f . . . 
. . . f f e e f f f f f f . . . 
. . . . f f f . . . f f . . . . 
`, img`
. . . . . f f f f f f . . . . . 
. . . . f b f e e e e f f . . . 
. . . f b b b f e e e e f f . . 
. . . f d d d d f f e e e f . . 
. . f d b b b b d d f f f f . . 
. . f b e f f f f b b b e f . . 
. . f f f e e e f f f f f f f . 
. . f e e 4 4 f b e 4 4 e f f . 
. . f f e d d f 1 4 d 4 e e f . 
. f d d f d d d d 4 e e e f . . 
. f b b f e e e 4 e e f f . . . 
. f b b e d d 4 b b b f . . . . 
. . f b e d d e b b b e . . . . 
. . . f f e e f 4 4 4 f . . . . 
. . . . . f f f f f f . . . . . 
. . . . . . . f f f . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . f f f f f f . . . . . 
. . . . f b f e e e e f f . . . 
. . . f b b b f e e e e f f . . 
. . . f d d d d f f e e e f . . 
. . f d b b b b d d f f f f . . 
. . f b e f f f f b b b e f . . 
. . f f f e e e f f f f f f f . 
. . f e e 4 4 f b e 4 4 e f f . 
. . f f e d d f 1 4 d 4 e e f . 
. f d d f d d d d 4 e e e f . . 
. f b b f e e e 4 e e f . . . . 
. f b b e d d 4 b b b f . . . . 
. . f b e d d e 4 4 4 f f . . . 
. . . f f e e f f f f f f . . . 
. . . . f f f . . . f f . . . . 
`];
            case "myAnim4":
            case "anim7":return [img`
. . . . f f f f f f . . . . . . 
. . . f b f e e e e f f . . . . 
. . f b b b f e e e e f f . . . 
. . f 1 1 1 1 f f e e e f . . . 
. f 1 b b b b 1 1 f f f f . . . 
. f b e f f f f b b b e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f b b b e d d 4 . . . . . 
. . . f b b b e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f b f e e e e f f . . . . 
. . f b b b f e e e e f f . . . 
. . f 1 1 1 1 f f e e e f . . . 
. f 1 b b b b 1 1 f f f f . . . 
. f b e f f f f b b b e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d e e e e e f . . . 
. . . f e 4 e d d 4 f . . . . . 
. . . f b b e d d e f . . . . . 
. . f f 5 5 f e e f f f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`, img`
. . . . f f f f f f . . . . . . 
. . . f b f e e e e f f . . . . 
. . f b b b f e e e e f f . . . 
. . f 1 1 1 1 f f e e e f . . . 
. f 1 b b b b 1 1 f f f f . . . 
. f b e f f f f b b b e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e e f f . . . . 
. . . f b b b e d d 4 . . . . . 
. . . f b b b e d d e . . . . . 
. . . f 5 5 4 f e e f . . . . . 
. . . . f f f f f f . . . . . . 
. . . . . . f f f . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . f f f f f f . . . . . . 
. . . f b f e e e e f f . . . . 
. . f b b b f e e e e f f . . . 
. . f 1 1 1 1 f f e e e f . . . 
. f 1 b b b b 1 1 f f f f . . . 
. f b e f f f f b b b e f . . . 
. f f f e e e f f f f f f f . . 
. f e e 4 4 f b e 4 4 e f f . . 
. . f e d d f 1 4 d 4 e e f . . 
. . . f d d d d 4 e e e f . . . 
. . . f e 4 4 4 e d d 4 . . . . 
. . . f b b b b e d d e . . . . 
. . f f 5 5 4 4 f e e f . . . . 
. . f f f f f f f f f f . . . . 
. . . f f f . . . f f . . . . . 
`];
            case "heroFrontAttack":
            case "anim10":return [img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
........................
........................
........................
........................
........................
........................
`, img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4f222222f1edde.......
fcf.f222222f44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "Walking Animation":
            case "anim1":return [img`
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. . f d b f f f f f f b d f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f f f f d d d d d e e f . . 
. f d d d d f 4 4 4 e e f . . . 
. f b b b b f b b b b f 4 e . . 
. f b b b b f b b b b f d 4 . . 
. . f c c f e 5 5 e e f 4 4 . . 
. . . f f f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. f f d b f f f f f f b d f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f . . 
. f f e 4 1 f d d f 1 4 e f . . 
f d f f e 4 d d d d 4 e f e . . 
f b f e f b b b b e d d 4 e . . 
f b f 4 f b b b b e d d e . . . 
f c f . f e e 5 5 f e e . . . . 
. f f . f f f f f f f . . . . . 
. . . . f f f . . . . . . . . . 
`, img`
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. . f d b f f f f f f b d f . . 
. . f f f f e e e e f f f f . . 
. f f e f b f 4 4 f b f e f f . 
. f e e 4 1 f d d f 1 4 e e f . 
. . f f f f d d d d d e e f . . 
. f d d d d f 4 4 4 e e f . . . 
. f b b b b f b b b b f 4 e . . 
. f b b b b f b b b b f d 4 . . 
. . f c c f e 5 5 e e f 4 4 . . 
. . . f f f f f f f f . . . . . 
. . . . . f f . . f f . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . f f f b b f f f . . . . 
. . . f f f b b b b f f f . . . 
. . f f f d d d d d d f f f . . 
. . f f d b b b b b b d f f . . 
. f f d b f f f f f f b d f f . 
. f f f f f e e e e f f f f f . 
. . f e f b f 4 4 f b f e f f . 
. . f e 4 1 f d d f 1 4 e f f . 
. . e f e 4 d d d d 4 e f f d f 
. . e 4 d d e b b b b f e f b f 
. . . e d d e b b b b f 4 f b f 
. . . . e e f 5 5 e e f . f c f 
. . . . . f f f f f f f . f f . 
. . . . . . . . . f f f . . . . 
`];
            case "myAnim3":
            case "anim6":return [img`
.....ffff...............
...fffbbfff.............
..fffbbbbfff............
.fffddddddfff...........
.ffdbbbbbbddf...........
.febffffffbef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbfbbbbf4e...........
fbbbbfbbbbfd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
......ffff..............
....fffbbfff............
...fffbbbbfff...........
..fffddddddfff..........
..ffdbbbbbbddf..........
..febffffffbef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4fbbbbedde...........
fcf.fbbcccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
.......ff...............
.....ffbbff.............
...fffbbbbfff...........
..fffbbbbbbfff..........
..fffbbbbbbfff..........
..fe11111111eff.........
.ff1bbbbbbbb1ff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfefbbbbbf4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
.........c1c............
..........c.............
........................
........................
........................
........................
`, img`
......ffff..............
....fffbbfff............
...fffbbbbfff...........
..fffddddddfff..........
..ffdbbbbbbddf..........
..febffffffbef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc..
.fee4dddddd4eef.ccddc...
fdfeeddddd4eeffecddc....
fbffee4444ee4fddccc.....
fbf4fbbbbbbf1edde.......
fcf.fbbbbbbf44ee........
.ff.f445544f............
....ffffffff............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`, img`
.....ffff...............
...fffbbfff.............
..fffbbbbfff............
.fffddddddfff...........
.ffdbbbbbbddf...........
.febffffffbef...........
.ffffeeeeffff...........
ffefbf44fbfeff..........
fee41fddf14eef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbfbbbbf4e...........
fbbbbfbbbbfd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
........................
`];
            case "myAnim5":
            case "anim13":return [img`
. . . . . . . . . . . . . . . . 
. . . f f f f f f f f f . . . . 
. . f 1 1 1 1 1 1 1 1 1 f . . . 
. f d 1 1 1 1 1 1 1 1 1 1 f . . 
. f d 1 1 1 1 1 1 1 1 1 1 f . . 
f d d 1 1 1 1 1 1 1 1 1 1 1 f . 
f d d d 1 1 1 1 1 1 1 1 1 1 f . 
f d d f f f 1 1 1 f f f 1 1 f . 
f d d f f f 1 1 1 f f f 1 1 f . 
. f d d f f 1 1 1 f f 1 1 f . . 
. f d d d d 1 f 1 1 1 1 1 f . . 
. . f f d d d f 1 1 1 f f . . . 
. . . . f d d 1 1 1 f . . . . . 
. . . . f d f 1 f 1 f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . f f f f f f f f f . . . . 
. . f 1 1 1 1 1 1 1 1 1 f . . . 
. f d 1 1 1 1 1 1 1 1 1 1 f . . 
. f d 1 1 1 1 1 1 1 1 1 1 f . . 
f d d 1 1 1 1 1 1 1 1 1 1 1 f . 
f d d d 1 1 1 1 1 1 1 1 1 1 f . 
f d d f f f 1 1 1 f f f 1 1 f . 
f d d f f f 1 1 1 f f f 1 1 f . 
. f d d f f 1 1 1 f f 1 1 f . . 
. f d d d d 1 f 1 1 1 1 1 f . . 
. . f f d d d f 1 1 1 f f . . . 
. . . . f d d 1 1 1 f . . . . . 
. . . . f d f 1 f 1 f . . . . . 
. . . . . f f f f f . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . f f f f f f f f f . . . . 
. . f 1 1 1 1 1 1 1 1 1 f . . . 
. f d 1 1 1 1 1 1 1 1 1 1 f . . 
. f d 1 1 1 1 1 1 1 1 1 1 f . . 
f d d 1 1 1 1 1 1 1 1 1 1 1 f . 
f d d d 1 1 1 1 1 1 1 1 1 1 f . 
f d d f f f 1 1 1 f f f 1 1 f . 
f d d f f f 1 1 1 f f f 1 1 f . 
. f d d f f 1 1 1 f f 1 1 f . . 
. f d d d d 1 f 1 1 1 1 1 f . . 
. . f f d d d f 1 1 1 f f . . . 
. . . . f d d 1 1 1 f . . . . . 
. . . . f d f 1 f 1 f . . . . . 
. . . . . f f f f f . . . . . . 
`];
            case "heroSideAttackRight":
            case "anim12":return [img`
........................
........................
........................
.........ffffff.........
.......ffeeeefbf........
......ffeeeefbbbf.......
......feeeffddddf...cc..
......ffffddbbbbdf.cdc..
......febbbffffebfcddc..
.....fffffffeeeffcddc...
.....ffe44ebf44ecddc....
.....fee4d41fddecdc.....
......feee4dddedccc.....
.......ffee44e4dde......
........fbbbb44ee.......
........fbbbbebf........
........f444455f........
.........ffffff.........
..........fff...........
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
.........fff............
......fffffbf...........
....ffeeeeebbff.........
...ffeeeeeebbbff........
...feeeefffddddf........
...fffffdddbbbbdf.......
..fffebbbfffffebf.......
..fffffffffeeefff.....cc
..fefe44ebbf44eef...ccdc
...fee4d4bbfddef..ccddcc
....feee4dddddfeecdddc..
.....fbbbbbbbeeddcdcc...
.....f444445e44ddccc....
.....ffffffffeeee.......
.....fff...ff...........
........................
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
..........ff............
.......ffffbff..........
.....ffeeeefbff.........
....ffeeeeefbbff........
....feeeeffddddf........
....fffffddbbbbdf.......
...fffebbbffffebf.......
...ffffffffeeefff.......
...fefe44ebf44eef.......
....fee4d4bfddef........
.....feee4dddee.c.......
......fbbbbeeddeccccccc.
......f444e44ddecddddd..
......fffffeeee.ccccc...
.....ffffffff...c.......
.....fff..ff............
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........ffffff..........
......ffeeeefbf.........
.....ffeeeefbbbf........
.....feeeffddddf........
.....ffffddbbbbdf.......
.....febbbffffebf.......
....fffffffeeefff.......
....ffe44ebf44eef.......
....fee4d41fddef........
.....feee4ddddf.........
......fdde444ef.........
......fddebbccc.........
.......eefbbcdc.........
.......f4444cddc........
........fffffcddc.......
.........fff..cddc......
...............cdc......
................cc......
........................
........................
........................
`, img`
........................
........................
........................
.........ffffff.........
.......ffeeeefbf........
......ffeeeefbbbf.......
......feeeff1111f.......
......ffff11bbbb1f......
......febbbffffebf......
.....fffffffeeefff......
.....ffe44ebf44eef......
.....fee4d41fddef.......
......feee4ddddf........
.......ffee444ef........
........4ddebbbf........
........eddebbbf........
........feef455f........
.........ffffff.........
..........fff...........
........................
........................
........................
........................
........................
`];
            case "heroSideAttackLeft":
            case "anim11":return [img`
........................
........................
........................
........................
.........ffffff.........
........fbfeeeeff.......
.......fbbbfeeeeff......
..cc...fddddffeeef......
..cdc.fdbbbbddffff......
..cddcfbeffffbbbef......
...cddcffeeefffffff.....
....cddce44fbe44eff.....
.....cdceddf14d4eef.....
.....cccdeddd4eeef......
......edd4e44eeff.......
.......ee44bbbbf........
........fbebbbbf........
........f554444f........
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
............fff.........
...........fbfffff......
.........ffbbeeeeeff....
........ffbbbeeeeeeff...
........fddddfffeeeef...
.......fdbbbbdddfffff...
.......fbefffffbbbefff..
cc.....fffeeefffffffff..
cdcc...fee44fbbe44efef..
ccddcc..feddfbb4d4eef...
..cdddceefddddd4eeef....
...ccdcddeebbbbbbbf.....
....cccdd44e544444f.....
.......eeeeffffffff.....
...........ff...fff.....
........................
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
............ff..........
..........ffbffff.......
.........ffbfeeeeff.....
........ffbbfeeeeeff....
........fddddffeeeef....
.......fdbbbbddfffff....
.......fbeffffbbbefff...
.......fffeeeffffffff...
.......fee44fbe44efef...
........feddfb4d4eef....
.......c.eeddd4eeef.....
.ccccccceddeebbbbf......
cddddddcedd44e444f......
.ccccccc.eeeefffff......
.......c...ffffffff.....
............ff..fff.....
........................
........................
........................
........................
`, img`
........................
........................
........................
........................
..........ffffff........
.........fbfeeeeff......
........fbbbfeeeeff.....
........fddddffeeef.....
.......fdbbbbddffff.....
.......fbeffffbbbef.....
.......fffeeefffffff....
.......fee44fbe44eff....
........feddf14d4eef....
.........fdddd4eeef.....
.........fe444eddf......
.........cccbbeddf......
.........cdcbbfee.......
........cddc4444f.......
.......cddcfffff........
......cddc..fff.........
......cdc...............
......cc................
........................
........................
`, img`
........................
........................
........................
........................
.........ffffff.........
........fbfeeeeff.......
.......fbbbfeeeeff......
.......fddddffeeef......
......fdbbbbddffff......
......fbeffffbbbef......
......fffeeefffffff.....
......fee44fbe44eff.....
......ffeddf14d4eef.....
.....fddfdddd4eeef......
.....fbbfeee4eeff.......
.....fbbedd4bbbf........
......fbeddebbbe........
.......ffeef444f........
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`];
            case "myAnim6":
            case "anim14":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . e . . . . 
. . . . . . . . . e e . . . . . 
. . . . . . . . e e . . . . . . 
. . . . . . . e e . . . . . . . 
. . . . . . e e . . . . . . . . 
. . . . . e e . . . . . . . . . 
. . . . e e . . . . . . . . . . 
. . . e e . . . . . . . . . . . 
. . e e e . . . . . . . . . . . 
. e e e . . . . . . . . . . . . 
. e e . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . e . . . . 
. . . . . . . . . e e . . . . . 
. . . . . . . . e e . . . . . . 
. . . . . . . e e . . . . . . . 
. . . . . . e e . . . . . . . . 
. . . . . e e . . . . . . . . . 
. . . . e e . . . . . . . . . . 
. . . e e . . . . . . . . . . . 
. . e e e . . . . . . . . . . . 
. e e e . . . . . . . . . . . . 
. e e . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . e . . . . 
. . . . . . . . . e e . . . . . 
. . . . . . . . e e . . . . . . 
. . . . . . . e e . . . . . . . 
. . . . . . e e . . . . . . . . 
. . . . . e e . . . . . . . . . 
. . . . e e . . . . . . . . . . 
. . . e e . . . . . . . . . . . 
. . e e e . . . . . . . . . . . 
. e e e . . . . . . . . . . . . 
. e e . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim7":
            case "anim15":return [img`
. . . . . . f f f f f . . . . . . . 
. . . . f f 1 1 1 1 1 f f . . . . . 
. . . f 1 1 1 1 1 1 1 1 1 f . . . . 
. . f 1 1 1 1 1 1 1 1 1 1 1 f . . . 
. . f 1 1 1 1 1 1 1 1 1 1 1 f . . . 
. f 1 1 1 f 1 1 f 1 1 1 1 1 1 f . . 
. f 1 1 f f 1 1 f f 1 1 1 1 1 f . . 
. f 1 f f f 1 1 f f f 1 1 1 1 f . . 
. f 1 1 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f 1 1 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f 1 1 1 1 f f 1 1 1 f f 1 1 f . . 
f 1 f 1 1 1 1 1 1 1 f 1 1 1 1 f . . 
f 1 f f 1 1 1 1 1 1 f 1 f 1 1 1 f . 
. f . . f f 1 1 1 1 f f 1 1 1 1 1 f 
. . . . . . f f f 1 1 1 1 1 1 1 f . 
. . . . . . . . . f f f f f f f . . 
`, img`
. . . . . . f f f f f . . . . . . . 
. . . . f f 1 1 1 1 1 f f . . . . . 
. . . f 1 1 1 1 1 1 1 1 1 f . . . . 
. . f 1 1 1 1 1 1 1 1 1 1 1 f . . . 
. . f 1 1 1 1 1 1 1 1 1 1 1 f . . . 
. f 1 1 1 f 1 1 f 1 1 1 1 1 1 f . . 
. f 1 1 f f 1 1 f f 1 1 1 1 1 f . . 
. f 1 f f f 1 1 f f f 1 1 1 1 f . . 
. f 1 1 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f 1 1 1 1 1 1 1 1 1 1 1 1 1 f . . 
. f 1 1 1 1 f f 1 1 1 f f 1 1 f . . 
f 1 f 1 1 1 1 1 1 1 f 1 1 1 1 f . . 
f 1 f f 1 1 1 1 1 1 f 1 f 1 1 1 f . 
. f . . f f 1 1 1 1 f f 1 1 1 1 1 f 
. . . . . . f f f 1 1 1 1 1 1 1 f . 
. . . . . . . . . f f f f f f f . . 
`];
            case "myAnim8":
            case "anim16":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . f f f f f . . . . . . 
. . . . f 5 5 5 5 5 f . . . . . 
. . . . f 5 5 5 5 5 5 f . . . . 
. . . f 5 f 5 5 5 f 5 f . . . . 
. . . f 5 f 5 5 5 f 5 7 f . . . 
. . . f 5 5 5 5 5 5 5 7 f . . . 
. . . . f 7 7 7 7 7 7 f . . . . 
. . . . . f f f f f f f . . . . 
. . . f f 5 5 f 5 5 7 f f . . . 
. . f 5 5 5 f 5 5 5 7 f 7 f . . 
. f 5 5 f 7 7 7 7 7 f 5 7 7 f . 
. f 7 5 5 f f f f f 5 5 7 f 7 f 
. f 7 5 5 5 5 5 5 5 5 5 7 f 7 f 
. . f 7 7 7 7 7 7 7 7 7 f f 7 f 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
